---
- name: Install a Apache
  hosts: web3, web1
  gather_facts: yes
  # become: true                          # sudo
  tasks:
  
  - name: Update_Cache - Install apache2 and php packages for Ubuntu/Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]


  - name: Update_Cache - Install httpd and php packages for RHEL-Distribution
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
      
  - name: Enable and start httpd because it doesnt start automatically
    service:
      name: httpd
      enabled: true
      state: started
    when: ansible_distribution == "AlmaLinux"

