---
- name: Install a Apache
  hosts: web1
  become: true                          # sudo
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution in ["AlmaLinux", "CentOS"]
      
  - name: Install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "AlmaLinux"
      
  - name: Add PHP support for HTTPD
    yum:
      name: php
      state: latest
    when: ansible_distribution == "AlmaLinux"
      
  - name: Enable and start Apache2
    service:
      name: httpd
      enabled: true
      state: started
    when: ansible_distribution == "AlmaLinux"

