---
- name: Update the server
  hosts: all
  gather_facts: yes
  # become: true                          # sudo
  pre_tasks:                              # This task must run first!!!

  - name: Install updates (RHEL) FIRST
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == ["AlmaLinux"]

  - name: Install Updates (Debian) FIRST
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]



- name: Install the Packages
  hosts: web_servers
  tasks:

  - name: Install apache2 and mod-php packages for Ubuntu/Debian
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]


  - name: Install httpd and php packages for RHEL-Distribution
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"
      
  - name: Enable and start httpd (RHEL and CentOS) because it doesnt start automatically
    service:
      name: httpd
      enabled: true
      state: started
    when: ansible_distribution == "AlmaLinux"


- name: next Play No. 3
  hosts: db_servers
  tasks:
  
  - name: Install mariadb package (RHEL)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: Install mariadb package (Debian) 
    tags: db, mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- name: next Play No. 4
  hosts: file_servers
  tasks:
  
  - name: Install samba package, same name for RHEL and Debian
    tags: samba
    package:          # Modul: package (samba has same name for RHEL + Debian)
      name: samba
      state: latest

