---
- name: Update the server
  hosts: all
  gather_facts: yes
  # become: true                          # sudo
  pre_tasks:                              # This task must run first!!!

  - name: Install updates (RHEL) FIRST
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == ["AlmaLinux"]

  - name: Install Updates (Debian) FIRST
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]





# Add new play only in workstation
- name: Install unzip and terraform in workstation.local
  hosts: myself
  gather_facts: yes
  tasks:
    
  - name: install unzip
    package:
      name: unzip

  - name: getting terraform link from website
    unarchive:              # module that allows to unzip the zipped file
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes       # the archive file already on remote system!
      mode: 0755
      owner: root
      group: root





# --------------------------------------------------------------------------------------
- name: Install the Packages
  hosts: web_servers
  tasks:

  - name: Install apache2 and mod-php packages for Ubuntu/Debian
    tags: apache,apache2,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]


  - name: Install httpd and php packages for RHEL-Distribution
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"
      
  - name: Enable and start httpd (RHEL and CentOS) because it doesnt start automatically
    service:
      name: httpd
      enabled: true
      state: started
    when: ansible_distribution == "AlmaLinux"

  - name: copy default html file for website
    tags: apache,apache2,httpd
    copy:
      src: default_site.html            # in /files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- name: next Play No. 3
  hosts: db_servers
  tasks:
  
  - name: Install mariadb package (RHEL)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: Install mariadb package (Debian) 
    tags: db, mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- name: next Play No. 4
  hosts: file_servers
  tasks:
  
  - name: Install samba package, same name for RHEL and Debian
    tags: samba
    package:          # Modul: package (samba has same name for RHEL + Debian)
      name: samba
      state: latest

