---
- name: Update the repo cache 
  hosts: all
  gather_facts: yes
  # become: true                          # sudo
  pre_tasks:                              # This task must run first!!!

  - name: update repo cache (RHEL)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false                   # when update_cache doesnt work, we see why!
    when: ansible_distribution == ["AlmaLinux"]

  - name: update repo cache (Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu", "Debian"]

# ------------------------------------------------------------------------------
# roles beginning
#
- name: --- Roles base ---
  hosts: all
  roles:
    - base

- name: --- Roles workstation ---
  hosts: workstation
  roles:
    - workstation

- name: --- Roles web_servers ---
  hosts: web_servers
  roles:
    - web_servers

- name: --- Roles db_servers ---
  hosts: db_servers
  roles:
    - db_servers

- name: --- Roles file_servers ---
  hosts: file_servers
  roles:
    - file_servers

